#ifndef VMM_TEST_MEM_COMPAT_VM_VM_PAGE_H
#define VMM_TEST_MEM_COMPAT_VM_VM_PAGE_H

#define VM_ALLOC_NORMAL		0x01
#define VM_ALLOC_SYSTEM		0x02
#define VM_ALLOC_ZERO		0x04
#define VM_ALLOC_RETRY		0x08

#endif /* VMM_TEST_MEM_COMPAT_VM_VM_PAGE_H */
