/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Fixed guest-physical PCIe apertures for the first vPCIe root.
 */
#ifndef VMM_PCIE_LAYOUT_H
#define VMM_PCIE_LAYOUT_H

#define VMM_PCIE_MMIO_BASE	0xc0000000ULL
#define VMM_PCIE_MMIO_SIZE	0x20000000ULL
#define VMM_PCIE_MMIO_END	(VMM_PCIE_MMIO_BASE + VMM_PCIE_MMIO_SIZE)

#define VMM_PCIE_ECAM_BASE	0xe0000000ULL
#define VMM_PCIE_ECAM_SIZE	0x10000000ULL
#define VMM_PCIE_ECAM_END	(VMM_PCIE_ECAM_BASE + VMM_PCIE_ECAM_SIZE)

#endif /* VMM_PCIE_LAYOUT_H */
