KMOD=	nvkm
SRCS=	nvkm.c nvkm_pci.c nvkm_bios.c nvkm_falcon.c nvkm_fw.c nvkm_sec2.c nvkm_gsp.c nvkm_gsp_meta.c nvkm_gsp_boot.c nvkm_gsp_libos.c \
	nvkm_mem.c nvkm_booter.c nvkm_fwsec.c
SRCS+=	device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
