/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * PCI IDs from Linux v7.1 amdgpu_drv.c (RDNA1/RDNA2 named).
 * Newer ASICs (RDNA3+, e.g. RX 9700) use IP discovery catch-all.
 * Generated by scripts/gen_amdrdna_chip.py — re-run after refreshing the table.
 */

#include "amdgpu_chip.h"

#include <sys/param.h>
#include <sys/systm.h>
#include <bus/pci/pcireg.h>

static const struct amdgpu_chip_info amdgpu_chip_navi10 = {
	.chip_id = AMDGPU_CHIP_NAVI10,
	.family = AMDGPU_FAMILY_RDNA1,
	.codename = "navi10",
	.family_name = "RDNA1",
	.is_apu = false,
};

static const struct amdgpu_chip_info amdgpu_chip_navi12 = {
	.chip_id = AMDGPU_CHIP_NAVI12,
	.family = AMDGPU_FAMILY_RDNA1,
	.codename = "navi12",
	.family_name = "RDNA1",
	.is_apu = false,
};

static const struct amdgpu_chip_info amdgpu_chip_navi14 = {
	.chip_id = AMDGPU_CHIP_NAVI14,
	.family = AMDGPU_FAMILY_RDNA1,
	.codename = "navi14",
	.family_name = "RDNA1",
	.is_apu = false,
};

static const struct amdgpu_chip_info amdgpu_chip_cyan_skillfish = {
	.chip_id = AMDGPU_CHIP_CYAN_SKILLFISH,
	.family = AMDGPU_FAMILY_RDNA1,
	.codename = "cyan_skillfish",
	.family_name = "RDNA1",
	.is_apu = true,
};

static const struct amdgpu_chip_info amdgpu_chip_sienna_cichlid = {
	.chip_id = AMDGPU_CHIP_SIENNA_CICHLID,
	.family = AMDGPU_FAMILY_RDNA2,
	.codename = "sienna_cichlid",
	.family_name = "RDNA2",
	.is_apu = false,
};

static const struct amdgpu_chip_info amdgpu_chip_navy_flounder = {
	.chip_id = AMDGPU_CHIP_NAVY_FLOUNDER,
	.family = AMDGPU_FAMILY_RDNA2,
	.codename = "navy_flounder",
	.family_name = "RDNA2",
	.is_apu = false,
};

static const struct amdgpu_chip_info amdgpu_chip_vangogh = {
	.chip_id = AMDGPU_CHIP_VANGOGH,
	.family = AMDGPU_FAMILY_RDNA2,
	.codename = "vangogh",
	.family_name = "RDNA2",
	.is_apu = true,
};

static const struct amdgpu_chip_info amdgpu_chip_dimgrey_cavefish = {
	.chip_id = AMDGPU_CHIP_DIMGREY_CAVEFISH,
	.family = AMDGPU_FAMILY_RDNA2,
	.codename = "dimgrey_cavefish",
	.family_name = "RDNA2",
	.is_apu = false,
};

static const struct amdgpu_chip_info amdgpu_chip_beige_goby = {
	.chip_id = AMDGPU_CHIP_BEIGE_GOBY,
	.family = AMDGPU_FAMILY_RDNA2,
	.codename = "beige_goby",
	.family_name = "RDNA2",
	.is_apu = false,
};

static const struct amdgpu_chip_info amdgpu_chip_yellow_carp = {
	.chip_id = AMDGPU_CHIP_YELLOW_CARP,
	.family = AMDGPU_FAMILY_RDNA2,
	.codename = "yellow_carp",
	.family_name = "RDNA2",
	.is_apu = true,
};

static const struct amdgpu_chip_info amdgpu_chip_ip_discovery = {
	.chip_id = AMDGPU_CHIP_IP_DISCOVERY,
	.family = AMDGPU_FAMILY_IP_DISCOVERY,
	.codename = "ip_discovery",
	.family_name = "RDNA3+",
	.is_apu = false,
};

static const struct amdgpu_pci_id amdgpu_pci_ids[] = {
	{ 0x13DB, "AMD cyan_skillfish (0x13DB)", &amdgpu_chip_cyan_skillfish },
	{ 0x13F9, "AMD cyan_skillfish (0x13F9)", &amdgpu_chip_cyan_skillfish },
	{ 0x13FA, "AMD cyan_skillfish (0x13FA)", &amdgpu_chip_cyan_skillfish },
	{ 0x13FB, "AMD cyan_skillfish (0x13FB)", &amdgpu_chip_cyan_skillfish },
	{ 0x13FC, "AMD cyan_skillfish (0x13FC)", &amdgpu_chip_cyan_skillfish },
	{ 0x13FE, "AMD cyan_skillfish (0x13FE)", &amdgpu_chip_cyan_skillfish },
	{ 0x143F, "AMD cyan_skillfish (0x143F)", &amdgpu_chip_cyan_skillfish },
	{ 0x163F, "AMD Van Gogh [RDNA2 APU]", &amdgpu_chip_vangogh },
	{ 0x164D, "AMD yellow_carp (0x164D)", &amdgpu_chip_yellow_carp },
	{ 0x1681, "AMD yellow_carp (0x1681)", &amdgpu_chip_yellow_carp },
	{ 0x7310, "AMD Navi 10", &amdgpu_chip_navi10 },
	{ 0x7312, "AMD navi10 (0x7312)", &amdgpu_chip_navi10 },
	{ 0x7318, "AMD navi10 (0x7318)", &amdgpu_chip_navi10 },
	{ 0x7319, "AMD navi10 (0x7319)", &amdgpu_chip_navi10 },
	{ 0x731A, "AMD navi10 (0x731A)", &amdgpu_chip_navi10 },
	{ 0x731B, "AMD navi10 (0x731B)", &amdgpu_chip_navi10 },
	{ 0x731E, "AMD navi10 (0x731E)", &amdgpu_chip_navi10 },
	{ 0x731F, "AMD Navi 10 [Radeon RX 5600/5700]", &amdgpu_chip_navi10 },
	{ 0x7340, "AMD Navi 14 [Radeon RX 5500]", &amdgpu_chip_navi14 },
	{ 0x7341, "AMD navi14 (0x7341)", &amdgpu_chip_navi14 },
	{ 0x7347, "AMD navi14 (0x7347)", &amdgpu_chip_navi14 },
	{ 0x734F, "AMD navi14 (0x734F)", &amdgpu_chip_navi14 },
	{ 0x7360, "AMD navi12 (0x7360)", &amdgpu_chip_navi12 },
	{ 0x7362, "AMD navi12 (0x7362)", &amdgpu_chip_navi12 },
	{ 0x73A0, "AMD sienna_cichlid (0x73A0)", &amdgpu_chip_sienna_cichlid },
	{ 0x73A1, "AMD sienna_cichlid (0x73A1)", &amdgpu_chip_sienna_cichlid },
	{ 0x73A2, "AMD sienna_cichlid (0x73A2)", &amdgpu_chip_sienna_cichlid },
	{ 0x73A3, "AMD sienna_cichlid (0x73A3)", &amdgpu_chip_sienna_cichlid },
	{ 0x73A5, "AMD sienna_cichlid (0x73A5)", &amdgpu_chip_sienna_cichlid },
	{ 0x73A8, "AMD sienna_cichlid (0x73A8)", &amdgpu_chip_sienna_cichlid },
	{ 0x73A9, "AMD sienna_cichlid (0x73A9)", &amdgpu_chip_sienna_cichlid },
	{ 0x73AB, "AMD sienna_cichlid (0x73AB)", &amdgpu_chip_sienna_cichlid },
	{ 0x73AC, "AMD sienna_cichlid (0x73AC)", &amdgpu_chip_sienna_cichlid },
	{ 0x73AD, "AMD sienna_cichlid (0x73AD)", &amdgpu_chip_sienna_cichlid },
	{ 0x73AE, "AMD sienna_cichlid (0x73AE)", &amdgpu_chip_sienna_cichlid },
	{ 0x73AF, "AMD sienna_cichlid (0x73AF)", &amdgpu_chip_sienna_cichlid },
	{ 0x73BF, "AMD Navi 21 [Radeon RX 6800/6900]", &amdgpu_chip_sienna_cichlid },
	{ 0x73C0, "AMD navy_flounder (0x73C0)", &amdgpu_chip_navy_flounder },
	{ 0x73C1, "AMD navy_flounder (0x73C1)", &amdgpu_chip_navy_flounder },
	{ 0x73C3, "AMD navy_flounder (0x73C3)", &amdgpu_chip_navy_flounder },
	{ 0x73DA, "AMD navy_flounder (0x73DA)", &amdgpu_chip_navy_flounder },
	{ 0x73DB, "AMD navy_flounder (0x73DB)", &amdgpu_chip_navy_flounder },
	{ 0x73DC, "AMD navy_flounder (0x73DC)", &amdgpu_chip_navy_flounder },
	{ 0x73DD, "AMD navy_flounder (0x73DD)", &amdgpu_chip_navy_flounder },
	{ 0x73DE, "AMD navy_flounder (0x73DE)", &amdgpu_chip_navy_flounder },
	{ 0x73DF, "AMD Navi 22 [Radeon RX 6700]", &amdgpu_chip_navy_flounder },
	{ 0x73E0, "AMD dimgrey_cavefish (0x73E0)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73E1, "AMD dimgrey_cavefish (0x73E1)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73E2, "AMD dimgrey_cavefish (0x73E2)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73E3, "AMD dimgrey_cavefish (0x73E3)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73E8, "AMD dimgrey_cavefish (0x73E8)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73E9, "AMD dimgrey_cavefish (0x73E9)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73EA, "AMD dimgrey_cavefish (0x73EA)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73EB, "AMD dimgrey_cavefish (0x73EB)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73EC, "AMD dimgrey_cavefish (0x73EC)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73ED, "AMD dimgrey_cavefish (0x73ED)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73EF, "AMD dimgrey_cavefish (0x73EF)", &amdgpu_chip_dimgrey_cavefish },
	{ 0x73FF, "AMD Navi 23 [Radeon RX 6600]", &amdgpu_chip_dimgrey_cavefish },
	{ 0x7420, "AMD beige_goby (0x7420)", &amdgpu_chip_beige_goby },
	{ 0x7421, "AMD beige_goby (0x7421)", &amdgpu_chip_beige_goby },
	{ 0x7422, "AMD Navi 24 [Radeon RX 6400/6500]", &amdgpu_chip_beige_goby },
	{ 0x7423, "AMD beige_goby (0x7423)", &amdgpu_chip_beige_goby },
	{ 0x7424, "AMD beige_goby (0x7424)", &amdgpu_chip_beige_goby },
	{ 0x743F, "AMD beige_goby (0x743F)", &amdgpu_chip_beige_goby },
	{ 0, NULL, NULL }
};

const struct amdgpu_pci_id *
amdgpu_chip_lookup_device(uint16_t device)
{
	const struct amdgpu_pci_id *id;

	for (id = amdgpu_pci_ids; id->name != NULL; id++) {
		if (id->device == device)
			return (id);
	}
	return (NULL);
}

const char *
amdgpu_chip_id_name(enum amdgpu_chip_id id)
{
	switch (id) {
	case AMDGPU_CHIP_NAVI10: return ("navi10");
	case AMDGPU_CHIP_NAVI12: return ("navi12");
	case AMDGPU_CHIP_NAVI14: return ("navi14");
	case AMDGPU_CHIP_CYAN_SKILLFISH: return ("cyan_skillfish");
	case AMDGPU_CHIP_SIENNA_CICHLID: return ("sienna_cichlid");
	case AMDGPU_CHIP_NAVY_FLOUNDER: return ("navy_flounder");
	case AMDGPU_CHIP_VANGOGH: return ("vangogh");
	case AMDGPU_CHIP_DIMGREY_CAVEFISH: return ("dimgrey_cavefish");
	case AMDGPU_CHIP_BEIGE_GOBY: return ("beige_goby");
	case AMDGPU_CHIP_YELLOW_CARP: return ("yellow_carp");
	case AMDGPU_CHIP_IP_DISCOVERY: return ("ip_discovery");
	default: return ("unknown");
	}
}

const struct amdgpu_chip_info *
amdgpu_chip_resolve(uint16_t vendor, uint16_t device, uint8_t classb,
    uint8_t subclass)
{
	const struct amdgpu_pci_id *id;

	if (vendor != AMDGPU_PCI_VENDOR_AMD)
		return (NULL);

	id = amdgpu_chip_lookup_device(device);
	if (id != NULL && id->chip != NULL)
		return (id->chip);

	if (classb != PCIC_DISPLAY)
		return (NULL);
	if (subclass != PCIS_DISPLAY_VGA && subclass != PCIS_DISPLAY_OTHER &&
	    subclass != PCIS_DISPLAY_3D)
		return (NULL);

	/* Unlisted post-Navi dGPUs (RDNA3/4, e.g. RX 9700 family). */
	if (device >= 0x7310)
		return (&amdgpu_chip_ip_discovery);

	return (NULL);
}
